<%
Const COLUMN_CARD_COUNT = "CardCount"
Const COLUMN_CARD_ID = "CardId"
Const COLUMN_CARD_TYPE_ID = "CardTypeId"
Const COLUMN_CARD_TYPE_NAME = "CardTypeName"
Const COLUMN_CHARACTER_ID = "CharacterId"
Const COLUMN_CHARACTER_NAME = "CharacterName"
Const COLUMN_DELETE_ON_PLAY ="DeleteOnPlay"
Const COLUMN_DRAW_ORDER = "DrawOrder"
Const COLUMN_IN_DISCARD_PILE = "InDiscardPile"
Const COLUMN_IN_DRAW_PILE = "InDrawPile"
Const COLUMN_IN_HAND = "InHand"

Const TABLE_CARD_TYPES = "CardTypes"
Const TABLE_CARDS = "Cards"

Const VIEW_CARD_DETAILS = "CardDetails"
Const VIEW_CARD_TYPE_DETAILS = "CardTypeDetails"

%>
