Friend Module Tokens
    Friend Const TOKEN_CHARACTER As String = "character"
    Friend Const TOKEN_CREATE As String = "create"
    Friend Const TOKEN_DROP As String = "drop"
    Friend Const TOKEN_FORAGE As String = "forage"
    Friend Const TOKEN_GO As String = "go"
    Friend Const TOKEN_GROUND As String = "ground"
    Friend Const TOKEN_HAND As String = "hand"
    Friend Const TOKEN_HELP As String = "help"
    Friend Const TOKEN_INVENTORY As String = "inventory"
    Friend Const TOKEN_PLAY As String = "play"
    Friend Const TOKEN_RENAME As String = "rename"
    Friend Const TOKEN_STATUS As String = "status"
    Friend Const TOKEN_TAKE As String = "take"
    Friend Const TOKEN_CRAFT As String = "craft"
    Friend Const TOKEN_CARDS As String = "cards"
    Friend Const TOKEN_DIE As String = "die"
    Friend Const TOKEN_REST As String = "rest"
End Module
