Friend Module Columns
    Friend Const COLUMN_CHARACTER_ID = "CharacterId"
    Friend Const COLUMN_CHARACTER_NAME = "CharacterName"
    Friend Const COLUMN_CHARACTER_TYPE_ID = "CharacterTypeId"
    Friend Const COLUMN_DIRECTION_ID = "DirectionId"
    Friend Const COLUMN_DIRECTION_NAME = "DirectionName"
    Friend Const COLUMN_DISCORD_ID = "DiscordId"
    Friend Const COLUMN_FROM_LOCATION_ID = "FromLocationId"
    Friend Const COLUMN_GENERATOR_WEIGHT = "GeneratorWeight"
    Friend Const COLUMN_LAST_MODIFIED = "LastModified"
    Friend Const COLUMN_LOCATION_ID = "LocationId"
    Friend Const COLUMN_LOCATION_NAME = "LocationName"
    Friend Const COLUMN_OTHER_CHARACTER_ID = "OtherCharacterId"
    Friend Const COLUMN_PLAYER_ID = "PlayerId"
    Friend Const COLUMN_ROUTE_ID = "RouteId"
    Friend Const COLUMN_ROUTE_TYPE_ID = "RouteTypeId"
    Friend Const COLUMN_ROUTE_TYPE_NAME = "RouteTypeName"
    Friend Const COLUMN_TO_LOCATION_ID = "ToLocationId"
    Friend Const COLUMN_LOCATION_TYPE_ID = "LocationTypeId"
    Friend Const COLUMN_LOCATION_TYPE_NAME = "LocationTypeName"
End Module
