Friend Module Fields
    Friend Const FIELD_CHARACTER_ID = "CharacterId"
    Friend Const FIELD_CHARACTER_NAME = "CharacterName"
    Friend Const FIELD_CHARACTER_TYPE_ID = "CharacterTypeId"
    Friend Const FIELD_DIRECTION_ID = "DirectionId"
    Friend Const FIELD_DIRECTION_NAME = "DirectionName"
    Friend Const FIELD_DISCORD_ID = "DiscordId"
    Friend Const FIELD_FROM_LOCATION_ID = "FromLocationId"
    Friend Const FIELD_GENERATOR_WEIGHT = "GeneratorWeight"
    Friend Const FIELD_LOCATION_ID = "LocationId"
    Friend Const FIELD_LOCATION_NAME = "LocationName"
    Friend Const FIELD_PLAYER_ID = "PlayerId"
    Friend Const FIELD_ROUTE_ID = "RouteId"
    Friend Const FIELD_ROUTE_TYPE_ID = "RouteTypeId"
    Friend Const FIELD_ROUTE_TYPE_NAME = "RouteTypeName"
End Module
