Friend Module Parameters
    Friend Const PARAMETER_CHARACTER_ID = "@CharacterId"
    Friend Const PARAMETER_DIRECTION_ID = "@DirectionId"
    Friend Const PARAMETER_DIRECTION_NAME = "@DirectionName"
    Friend Const PARAMETER_DISCORD_ID = "@DiscordId"
    Friend Const PARAMETER_CHARACTER_NAME = "@CharacterName"
    Friend Const PARAMETER_CHARACTER_TYPE_ID = "@CharacterTypeId"
    Friend Const PARAMETER_GENERATOR_WEIGHT = "@GeneratorWeight"
    Friend Const PARAMETER_INVENTORY_ID = "@InventoryId"
    Friend Const PARAMETER_ITEM_TYPE_GENERATOR_ID = "@ItemTypeGeneratorId"
    Friend Const PARAMETER_ITEM_TYPE_GENERATOR_NAME = "@ItemTypeGeneratorName"
    Friend Const PARAMETER_ITEM_TYPE_ID = "@ItemTypeId"
    Friend Const PARAMETER_ITEM_TYPE_NAME = "@ItemTypeName"
    Friend Const PARAMETER_LAST_MODIFIED = "@LastModified"
    Friend Const PARAMETER_LOCATION_ID = "@LocationId"
    Friend Const PARAMETER_LOCATION_NAME = "@LocationName"
    Friend Const PARAMETER_LOCATION_TYPE_ID = "@LocationTypeId"
    Friend Const PARAMETER_LOCATION_TYPE_NAME = "@LocationTypeName"
    Friend Const PARAMETER_PLAYER_ID = "@PlayerId"
    Friend Const PARAMETER_ROUTE_ID = "@RouteId"
    Friend Const PARAMETER_ROUTE_TYPE_ID = "@RouteTypeId"
    Friend Const PARAMETER_FROM_LOCATION_ID = "@FromLocationId"
    Friend Const PARAMETER_TO_LOCATION_ID = "@ToLocationId"
    Friend Const PARAMETER_RECIPE_ID = "@RecipeId"
    Friend Const PARAMETER_QUANTITY_IN = "@QuantityIn"
End Module
