Friend Module Tables
    Friend Const TABLE_CARDS = "Cards"
    Friend Const TABLE_CARD_TYPE_GENERATOR_CARD_TYPES = "CardTypeGeneratorCardTypes"
    Friend Const TABLE_CARD_TYPE_GENERATORS = "CardTypeGenerators"
    Friend Const TABLE_CARD_TYPES = "CardTypes"
    Friend Const TABLE_CHARACTERS = "Characters"
    Friend Const TABLE_CHARACTER_STATISTICS = "CharacterStatistics"
    Friend Const TABLE_CHARACTER_TYPE_CARDS = "CharacterTypeCards"
    Friend Const TABLE_CHARACTER_TYPES = "CharacterTypes"
    Friend Const TABLE_CHARACTER_TYPE_STATISTICS = "CharacterTypeStatistics"
    Friend Const TABLE_EFFECT_TYPES = "EffectTypes"
    Friend Const TABLE_LOCATIONS = "Locations"
    Friend Const TABLE_LOCATION_STARTS = "LocationStarts"
    Friend Const TABLE_LOCATION_TYPES = "LocationTypes"
    Friend Const TABLE_PLAYER_CHARACTERS = "PlayerCharacters"
    Friend Const TABLE_PLAYERS = "Players"
    Friend Const TABLE_STATISTIC_TYPES = "StatisticTypes"
    Friend Const TABLE_CARD_TYPE_STATISTIC_REQUIREMENTS = "CardTypeStatisticRequirements"
    Friend Const TABLE_EFFECT_TYPE_STATISTIC_REQUIREMENTS = "EffectTypeStatisticRequirements"
End Module

