Friend Module Tables
    Friend Const TABLE_CHARACTERS = "Characters"
    Friend Const TABLE_DIRECTIONS = "Directions"
    Friend Const TABLE_LOCATION_STARTS = "LocationStarts"
    Friend Const TABLE_PLAYERS = "Players"
    Friend Const TABLE_PLAYER_CHARACTER_TYPES = "PlayerCharacterTypes"
    Friend Const TABLE_PLAYER_CHARACTERS = "PlayerCharacters"
    Friend Const TABLE_LOCATION_TYPES = "LocationTypes"
    Friend Const TABLE_LOCATIONS = "Locations"
    Friend Const TABLE_ROUTES = "Routes"
    Friend Const TABLE_ROUTE_TYPES = "RouteTypes"
    Friend Const TABLE_ITEM_TYPES = "ItemTypes"
    Friend Const TABLE_ITEM_TYPE_GENERATORS = "ItemTypeGenerators"
    Friend Const TABLE_ITEM_TYPE_GENERATOR_ITEM_TYPES = "ItemTypeGeneratorItemTypes"
    Friend Const TABLE_INVENTORIES = "Inventories"
    Friend Const TABLE_ITEMS = "Items"
End Module
