Friend Module Views
    Friend Const VIEW_CHARACTER_LOCATION_OTHER_CHARACTERS = "CharacterLocationOtherCharacters"
    Friend Const VIEW_ITEM_DETAILS = "ItemDetails"
    Friend Const VIEW_ITEM_TYPE_GENERATOR_AVAILABLE_ITEM_TYPES = "ItemTypeGeneratorAvailableItemTypes"
    Friend Const VIEW_ITEM_TYPE_GENERATOR_ITEM_TYPE_DETAILS = "ItemTypeGeneratorItemTypeDetails"
    Friend Const VIEW_INVENTORY_ITEM_DETAILS = "InventoryItemDetails"
    Friend Const VIEW_ROUTE_DETAILS = "RouteDetails"
    Friend Const VIEW_LOCATION_AVAILABLE_DIRECTIONS = "LocationAvailableDirections"
    Friend Const VIEW_RECIPE_AVAILABLE_ITEM_TYPES = "RecipeAvailableItemTypes"
    Friend Const VIEW_RECIPE_ITEM_TYPE_DETAILS = "RecipeItemTypeDetails"
    Friend Const VIEW_INVENTORY_ITEM_TYPE_COUNTS = "InventoryItemTypeCounts"
    Friend Const VIEW_CARD_DETAILS = "CardDetails"
    Friend Const VIEW_CHARACTER_TYPE_STATISTIC_DETAILS = "CharacterTypeStatisticDetails"
    Friend Const VIEW_CHARACTER_TYPE_AVAILABLE_STATISTIC_TYPES = "CharacterTypeAvailableStatisticTypes"
    Friend Const VIEW_CHARACTER_STATISTIC_DETAILS = "CharacterStatisticDetails"
    Friend Const VIEW_CHARACTER_AVAILABLE_STATISTICS = "CharacterAvailableStatistics"
    Friend Const VIEW_CHARACTER_TYPE_CARD_DETAILS = "CharacterTypeCardDetails"
    Friend Const VIEW_CHARACTER_TYPE_AVAILABLE_CARD_TYPES = "CharacterTypeAvailableCards"
End Module
